<?php

namespace Zuqongtech\LaravelAnvil\Generators;

use Illuminate\Support\Str;
use Zuqongtech\LaravelAnvil\Contracts\Generator;
use Zuqongtech\LaravelAnvil\Support\GenerationOptions;
use Zuqongtech\LaravelAnvil\Support\Helpers;
use Zuqongtech\LaravelAnvil\Support\ModelMetadata;

/**
 * Generates Livewire 3 components for the web scaffold when --stack=livewire.
 *
 * Per resource, three component/view pairs:
 *   App\Livewire\{Plural}\Index  + livewire/{slug}/index.blade.php  — listing + delete
 *   App\Livewire\{Plural}\Form   + livewire/{slug}/form.blade.php   — create + update
 *   App\Livewire\{Plural}\Show   + livewire/{slug}/show.blade.php   — read-only detail
 *
 * GET requests still flow through the web controller, which renders a thin Blade
 * wrapper view (generated by ViewGenerator) that mounts the matching component:
 *
 *   GET  /posts          → PostController@index  → posts.index  → <livewire:posts.index/>
 *   GET  /posts/create   → PostController@create → posts.create → <livewire:posts.form/>
 *   GET  /posts/{id}/edit→ PostController@edit    → posts.edit   → <livewire:posts.form :record-id/>
 *   GET  /posts/{id}     → PostController@show    → posts.show   → <livewire:posts.show :record-id/>
 *
 * All writes (store/update/delete) happen inside the components via the shared
 * Service. Persistence is delegated to App\Services\{Model}Service; validation
 * rules are derived from column metadata.
 *
 * Blade is produced from nowdoc templates with %TOKEN% placeholders so PHP never
 * interpolates Livewire's wire: directives or Blade's {{ }} / $variables.
 */
final class LivewireComponentGenerator implements Generator
{
    private const SENSITIVE = ['password', 'remember_token', 'two_factor_secret', 'two_factor_recovery_codes'];

    public function supports(GenerationOptions $options): bool
    {
        return ($options->web ?? false) && $options->isLivewire();
    }

    public function getName(): string
    {
        return 'LivewireComponent';
    }

    public function generate(ModelMetadata $meta, GenerationOptions $options): array
    {
        $model       = $meta->model;
        $studlyPl    = Str::pluralStudly($model);                 // VehicleCategories
        $slug        = Helpers::modelToRouteName($model);         // vehicle-categories
        $var         = lcfirst($model);                           // vehicleCategory
        $pluralVar   = lcfirst($studlyPl);                        // vehicleCategories
        $title       = Str::headline($model);
        $titlePl     = Str::headline($studlyPl);
        $service     = $model.'Service';
        $lwNamespace = trim($options->getLivewireNamespace(), '\\').'\\'.$studlyPl;
        $serviceFqn  = 'App\\Services\\'.$service;

        $pk        = $this->resolvePk($meta);
        $formCols  = $this->formColumns($meta);
        $tableCols = $this->tableColumns($meta, $pk);
        $showCols  = $this->showColumns($meta);

        $ctx = compact('model', 'slug', 'var', 'pluralVar', 'title', 'titlePl', 'service', 'lwNamespace', 'serviceFqn', 'pk');

        $classDir = app_path('Livewire/'.$studlyPl);
        $viewDir  = resource_path('views/livewire/'.$slug);

        $files = [
            [$classDir.'/Index.php',                 $this->indexComponent($ctx)],
            [$viewDir.'/index.blade.php',            $this->indexView($ctx, $tableCols)],
            [$classDir.'/Form.php',                  $this->formComponent($ctx, $meta, $formCols)],
            [$viewDir.'/form.blade.php',             $this->formView($ctx, $formCols)],
            [$classDir.'/Show.php',                  $this->showComponent($ctx)],
            [$viewDir.'/show.blade.php',             $this->showView($ctx, $showCols)],
        ];

        $results = [];
        foreach ($files as [$path, $content]) {
            $name = basename($path);

            if (file_exists($path) && ! $options->force) {
                $results[] = $this->result($name, $path, 'skipped', 'already exists');
                continue;
            }

            if (! $options->dryRun) {
                $dir = dirname($path);
                if (! is_dir($dir)) {
                    mkdir($dir, 0755, true);
                }
                file_put_contents($path, $content);
            }

            $results[] = $this->result($name, $path, 'success');
        }

        return $results;
    }

    // -----------------------------------------------------------------------
    // Index component
    // -----------------------------------------------------------------------

    protected function indexComponent(array $c): string
    {
        return <<<PHP
<?php

namespace {$c['lwNamespace']};

use {$c['serviceFqn']};
use Illuminate\\Contracts\\View\\View;
use Livewire\\Component;
use Livewire\\WithPagination;

class Index extends Component
{
    use WithPagination;

    public int \$perPage = 15;

    protected function service(): {$c['service']}
    {
        return app({$c['service']}::class);
    }

    public function delete(int|string \$id): void
    {
        \$this->service()->delete(\$id);

        session()->flash('success', '{$c['title']} deleted.');

        \$this->resetPage();
    }

    public function render(): View
    {
        return view('livewire.{$c['slug']}.index', [
            '{$c['pluralVar']}' => \$this->service()->paginate(\$this->perPage),
        ]);
    }
}

PHP;
    }

    protected function indexView(array $c, array $tableCols): string
    {
        $head = '';
        $row  = '';
        foreach ($tableCols as $col) {
            $label = $this->label($col);
            $head .= "                    <th class=\"px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase\">{$label}</th>\n";
            $row  .= "                        <td class=\"px-4 py-3 text-sm text-gray-700\">{{ \$%VAR%->{$col} }}</td>\n";
        }

        $tpl = <<<'BLADE'
<div>
    <div class="flex items-center justify-between mb-6">
        <h2 class="text-2xl font-bold">%TITLE_PLURAL%</h2>
        <a href="{{ route('%SLUG%.create') }}" class="btn-primary">+ New %TITLE%</a>
    </div>

    @if (session('success'))
        <div class="mb-4 rounded-md bg-green-50 border border-green-200 px-4 py-3 text-green-800">
            {{ session('success') }}
        </div>
    @endif

    <div class="overflow-x-auto bg-white rounded-lg shadow">
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
                <tr>
%TABLE_HEAD%                    <th class="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Actions</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-100">
                @forelse ($%PLURAL_VAR% as $%VAR%)
                    <tr wire:key="%SLUG%-{{ $%VAR%->getKey() }}" class="hover:bg-gray-50">
%TABLE_ROW%                        <td class="px-4 py-3 text-right whitespace-nowrap">
                            <a href="{{ route('%SLUG%.show', $%VAR%) }}" class="link">View</a>
                            <a href="{{ route('%SLUG%.edit', $%VAR%) }}" class="link">Edit</a>
                            <button type="button" class="link-danger"
                                    wire:click="delete('{{ $%VAR%->getKey() }}')"
                                    wire:confirm="Delete this %TITLE%?">Delete</button>
                        </td>
                    </tr>
                @empty
                    <tr><td colspan="99" class="px-4 py-6 text-center text-gray-400">No %TITLE_PLURAL% found.</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="mt-4">
        {{ $%PLURAL_VAR%->links() }}
    </div>
</div>
BLADE;

        return $this->apply($tpl, ['%TABLE_HEAD%' => $head, '%TABLE_ROW%' => $row] + $this->tokens($c));
    }

    // -----------------------------------------------------------------------
    // Form component (create + update)
    // -----------------------------------------------------------------------

    protected function formComponent(array $c, ModelMetadata $meta, array $formCols): string
    {
        $props = '';
        $fillLines = '';
        $rules = '';

        foreach ($formCols as $col) {
            $name = $col['name'];
            $default = $this->propDefault($col);
            $props .= "    public {$this->propType($col)} \${$name} = {$default};\n";
            $fillLines .= "            \$this->{$name} = \$record->{$name};\n";
            $rules .= "            '{$name}' => ".$this->ruleArray($col).",\n";
        }

        $props = rtrim($props, "\n");
        $fillLines = rtrim($fillLines, "\n");
        $rules = rtrim($rules, "\n");

        return <<<PHP
<?php

namespace {$c['lwNamespace']};

use {$c['serviceFqn']};
use Illuminate\\Contracts\\View\\View;
use Livewire\\Component;

class Form extends Component
{
    public int|string|null \$recordId = null;

    public bool \$editing = false;

{$props}

    protected function service(): {$c['service']}
    {
        return app({$c['service']}::class);
    }

    public function mount(int|string|null \$recordId = null): void
    {
        if (\$recordId === null) {
            return;
        }

        \$record = \$this->service()->findOrFail(\$recordId);

        \$this->recordId = \$recordId;
        \$this->editing = true;

{$fillLines}
    }

    protected function rules(): array
    {
        return [
{$rules}
        ];
    }

    public function save(): void
    {
        \$data = \$this->validate();

        if (\$this->editing) {
            \$this->service()->update(\$this->recordId, \$data);
            \$message = '{$c['title']} updated.';
        } else {
            \$this->service()->create(\$data);
            \$message = '{$c['title']} created.';
        }

        session()->flash('success', \$message);

        \$this->redirectRoute('{$c['slug']}.index', navigate: true);
    }

    public function render(): View
    {
        return view('livewire.{$c['slug']}.form');
    }
}

PHP;
    }

    protected function formView(array $c, array $formCols): string
    {
        $fields = '';
        foreach ($formCols as $col) {
            $fields .= $this->formField($col);
        }

        $tpl = <<<'BLADE'
<div>
    <form wire:submit="save" class="bg-white rounded-lg shadow p-6">
%FORM_FIELDS%
        <div class="flex items-center gap-3 mt-6">
            <button type="submit" class="btn-primary">
                <span wire:loading.remove wire:target="save">{{ $editing ? 'Save changes' : 'Create' }}</span>
                <span wire:loading wire:target="save">Saving…</span>
            </button>
            <a href="{{ route('%SLUG%.index') }}" class="btn-secondary" wire:navigate>Cancel</a>
        </div>
    </form>
</div>
BLADE;

        return $this->apply($tpl, ['%FORM_FIELDS%' => rtrim($fields, "\n")] + $this->tokens($c));
    }

    // -----------------------------------------------------------------------
    // Show component
    // -----------------------------------------------------------------------

    protected function showComponent(array $c): string
    {
        return <<<PHP
<?php

namespace {$c['lwNamespace']};

use {$c['serviceFqn']};
use Illuminate\\Contracts\\View\\View;
use Livewire\\Component;

class Show extends Component
{
    public int|string \$recordId;

    public function mount(int|string \$recordId): void
    {
        \$this->recordId = \$recordId;
    }

    protected function service(): {$c['service']}
    {
        return app({$c['service']}::class);
    }

    public function render(): View
    {
        return view('livewire.{$c['slug']}.show', [
            '{$c['var']}' => \$this->service()->findOrFail(\$this->recordId),
        ]);
    }
}

PHP;
    }

    protected function showView(array $c, array $showCols): string
    {
        $rows = '';
        foreach ($showCols as $col) {
            $label = $this->label($col);
            $rows .= "        <div class=\"py-3 border-b border-gray-100\">\n"
                ."            <dt class=\"text-sm font-medium text-gray-500\">{$label}</dt>\n"
                ."            <dd class=\"text-gray-900\">{{ \$%VAR%->{$col} }}</dd>\n"
                ."        </div>\n";
        }

        $tpl = <<<'BLADE'
<div>
    <div class="flex items-center justify-between mb-6">
        <h2 class="text-2xl font-bold">%TITLE%</h2>
        <div>
            <a href="{{ route('%SLUG%.edit', $%VAR%) }}" class="btn-primary" wire:navigate>Edit</a>
            <a href="{{ route('%SLUG%.index') }}" class="btn-secondary" wire:navigate>Back</a>
        </div>
    </div>

    <dl class="bg-white rounded-lg shadow p-6">
%SHOW_ROWS%    </dl>
</div>
BLADE;

        return $this->apply($tpl, ['%SHOW_ROWS%' => $rows] + $this->tokens($c));
    }

    // -----------------------------------------------------------------------
    // Field rendering (wire:model inputs)
    // -----------------------------------------------------------------------

    protected function formField(array $col): string
    {
        $name  = $col['name'];
        $label = $this->label($name);
        $type  = $this->inputType($col);

        if ($type === 'textarea') {
            $control = "<textarea wire:model=\"{$name}\" rows=\"4\" class=\"form-input\"></textarea>";
        } elseif ($type === 'checkbox') {
            $control = "<input type=\"checkbox\" wire:model=\"{$name}\" class=\"rounded border-gray-300\">";
        } elseif ($type === 'select') {
            $options = '';
            foreach ($this->enumValues($col) as $opt) {
                $options .= "\n                <option value=\"{$opt}\">{$opt}</option>";
            }
            $control = "<select wire:model=\"{$name}\" class=\"form-input\">\n"
                ."                <option value=\"\">&mdash; Select &mdash;</option>{$options}\n            </select>";
        } else {
            $step = $type === 'number' && $this->isDecimal($col) ? ' step="any"' : '';
            $control = "<input type=\"{$type}\" wire:model=\"{$name}\"{$step} class=\"form-input\">";
        }

        return "        <div class=\"mb-4\">\n"
            ."            <label class=\"block text-sm font-medium text-gray-700 mb-1\">{$label}</label>\n"
            ."            {$control}\n"
            ."            @error('{$name}') <p class=\"text-sm text-red-600 mt-1\">{{ \$message }}</p> @enderror\n"
            ."        </div>\n";
    }

    // -----------------------------------------------------------------------
    // Validation rules + PHP property typing (derived from columns)
    // -----------------------------------------------------------------------

    protected function ruleArray(array $col): string
    {
        $rules = [];
        $rules[] = ($col['nullable'] ?? false) ? "'nullable'" : "'required'";

        $type = $this->inputType($col);
        $raw  = strtolower(preg_replace('/\(.*\)/', '', $col['type'] ?? 'varchar'));

        if ($type === 'checkbox') {
            $rules = ["'boolean'"];
        } elseif ($type === 'number') {
            $rules[] = $this->isDecimal($col) ? "'numeric'" : "'integer'";
        } elseif (in_array($type, ['date', 'datetime-local'], true)) {
            $rules[] = "'date'";
        } elseif ($type === 'email') {
            $rules[] = "'email'";
        } elseif ($type === 'url') {
            $rules[] = "'url'";
        } elseif (in_array($raw, ['varchar', 'char', 'string'], true)) {
            $rules[] = "'string'";
            if (! empty($col['length'])) {
                $rules[] = "'max:".((int) $col['length'])."'";
            } else {
                $rules[] = "'max:255'";
            }
        } elseif ($type === 'textarea') {
            $rules[] = "'string'";
        }

        return '['.implode(', ', $rules).']';
    }

    protected function propType(array $col): string
    {
        $type = $this->inputType($col);
        $nullable = ($col['nullable'] ?? false) ? '?' : '';

        return match ($type) {
            'checkbox' => 'bool',
            'number'   => $this->isDecimal($col) ? "{$nullable}float" : "{$nullable}int",
            default    => "{$nullable}string",
        };
    }

    protected function propDefault(array $col): string
    {
        $type = $this->inputType($col);

        if ($type === 'checkbox') {
            return 'false';
        }
        if (($col['nullable'] ?? false)) {
            return 'null';
        }

        return match ($type) {
            'number' => 'null',
            default  => "''",
        };
    }

    // -----------------------------------------------------------------------
    // Column selection / type inference (mirrors ViewGenerator)
    // -----------------------------------------------------------------------

    protected function formColumns(ModelMetadata $meta): array
    {
        $skip = array_merge(
            [$meta->primaryKey, 'created_at', 'updated_at', 'deleted_at', 'remember_token', 'password', 'email_verified_at'],
            $meta->compositePrimaryKey ?? [],
        );

        return array_values(array_filter(
            $meta->columns,
            fn ($c) => ! in_array($c['name'], $skip, true) && ! in_array($c['name'], self::SENSITIVE, true),
        ));
    }

    protected function tableColumns(ModelMetadata $meta, ?string $pk): array
    {
        $skip = ['deleted_at', 'updated_at'];
        $names = [];

        if ($pk !== null) {
            $names[] = $pk;
        }

        foreach ($meta->columns as $c) {
            if (count($names) >= 5) {
                break;
            }
            $n = $c['name'];
            if ($n === $pk || in_array($n, self::SENSITIVE, true) || in_array($n, $skip, true)) {
                continue;
            }
            if ($this->inputType($c) === 'textarea') {
                continue;
            }
            $names[] = $n;
        }

        if (empty($names) && ! empty($meta->columns)) {
            $names[] = $meta->columns[0]['name'];
        }

        return $names;
    }

    protected function showColumns(ModelMetadata $meta): array
    {
        return array_values(array_filter(
            array_column($meta->columns, 'name'),
            fn ($n) => ! in_array($n, self::SENSITIVE, true),
        ));
    }

    protected function resolvePk(ModelMetadata $meta): ?string
    {
        $columns = array_column($meta->columns, 'name');

        $candidates = array_merge([$meta->primaryKey], $meta->compositePrimaryKey ?? [], ['id']);
        foreach ($candidates as $cand) {
            if (is_string($cand) && $cand !== '' && in_array($cand, $columns, true)) {
                return $cand;
            }
        }

        return $columns[0] ?? null;
    }

    protected function inputType(array $col): string
    {
        $name = strtolower($col['name']);
        $raw  = strtolower($col['type'] ?? 'varchar');
        $type = preg_replace('/\(.*\)/', '', $raw);

        if (str_starts_with($raw, 'enum')) {
            return 'select';
        }
        if ($type === 'tinyint' && str_contains($raw, '(1)')) {
            return 'checkbox';
        }
        if (in_array($type, ['boolean', 'bool'], true)) {
            return 'checkbox';
        }
        if (in_array($type, ['text', 'mediumtext', 'longtext', 'tinytext', 'json', 'jsonb'], true)) {
            return 'textarea';
        }
        if (in_array($type, ['int', 'integer', 'bigint', 'smallint', 'mediumint', 'decimal', 'numeric', 'float', 'double', 'real'], true)) {
            return 'number';
        }
        if ($type === 'date') {
            return 'date';
        }
        if (in_array($type, ['datetime', 'timestamp'], true)) {
            return 'datetime-local';
        }
        if (str_contains($name, 'email')) {
            return 'email';
        }
        if (str_contains($name, 'url') || str_contains($name, 'website')) {
            return 'url';
        }

        return 'text';
    }

    protected function isDecimal(array $col): bool
    {
        $type = strtolower(preg_replace('/\(.*\)/', '', $col['type'] ?? ''));

        return in_array($type, ['decimal', 'numeric', 'float', 'double', 'real'], true);
    }

    /** @return list<string> */
    protected function enumValues(array $col): array
    {
        if (preg_match("/enum\\('(.+?)'\\)/i", $col['type'] ?? '', $m)) {
            return array_map('trim', explode("','", $m[1]));
        }

        return [];
    }

    protected function label(string $name): string
    {
        return Str::headline(preg_replace('/_id$/', '', $name));
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /** Simple-token map shared by all view templates. */
    protected function tokens(array $c): array
    {
        return [
            '%TITLE%'        => $c['title'],
            '%TITLE_PLURAL%' => $c['titlePl'],
            '%SLUG%'         => $c['slug'],
            '%VAR%'          => $c['var'],
            '%PLURAL_VAR%'   => $c['pluralVar'],
        ];
    }

    protected function apply(string $template, array $map): string
    {
        return str_replace(array_keys($map), array_values($map), $template);
    }

    protected function result(string $name, string $path, string $status, ?string $reason = null): array
    {
        $out = ['type' => $this->getName(), 'name' => $name, 'path' => $path, 'status' => $status];
        if ($reason !== null) {
            $out['reason'] = $reason;
        }

        return $out;
    }
}