<?php

namespace Zuqongtech\LaravelAnvil\Generators;

use Illuminate\Support\Str;
use Zuqongtech\LaravelAnvil\Contracts\Generator;
use Zuqongtech\LaravelAnvil\Support\GenerationOptions;
use Zuqongtech\LaravelAnvil\Support\Helpers;
use Zuqongtech\LaravelAnvil\Support\ModelMetadata;

/**
 * Generates Livewire 3 components for the web scaffold when --stack=livewire.
 *
 * Per resource, three component/view pairs:
 *   App\Livewire\{Plural}\Index  + livewire/{slug}/index.blade.php  — listing + delete
 *   App\Livewire\{Plural}\Form   + livewire/{slug}/form.blade.php   — create + update
 *   App\Livewire\{Plural}\Show   + livewire/{slug}/show.blade.php   — read-only detail
 *
 * GET requests still flow through the web controller, which renders a thin Blade
 * wrapper view (generated by ViewGenerator) that mounts the matching component:
 *
 *   GET  /posts          → PostController@index  → posts.index  → <livewire:posts.index/>
 *   GET  /posts/create   → PostController@create → posts.create → <livewire:posts.form/>
 *   GET  /posts/{id}/edit→ PostController@edit    → posts.edit   → <livewire:posts.form :record-id/>
 *   GET  /posts/{id}     → PostController@show    → posts.show   → <livewire:posts.show :record-id/>
 *
 * All writes (store/update/delete) happen inside the components via the shared
 * Service. Persistence is delegated to App\Services\{Model}Service; validation
 * rules are derived from column metadata.
 *
 * Blade is produced from nowdoc templates with %TOKEN% placeholders so PHP never
 * interpolates Livewire's wire: directives or Blade's {{}} / $variables.
 */
final class LivewireComponentGenerator implements Generator
{
    private const SENSITIVE = ['password', 'remember_token', 'two_factor_secret', 'two_factor_recovery_codes'];

    public function supports(GenerationOptions $options): bool
    {
        return ($options->web ?? false) && $options->isLivewire();
    }

    public function getName(): string
    {
        return 'LivewireComponent';
    }

    public function generate(ModelMetadata $meta, GenerationOptions $options): array
    {
        $model = $meta->model;
        $studlyPl = Str::pluralStudly($model);                 // VehicleCategories
        $slug = Helpers::modelToRouteName($model);         // vehicle-categories
        $var = lcfirst($model);                           // vehicleCategory
        $pluralVar = lcfirst($studlyPl);                        // vehicleCategories
        $title = Str::headline($model);
        $titlePl = Str::headline($studlyPl);
        $service = $model.'Service';
        $lwNamespace = trim($options->getLivewireNamespace(), '\\').'\\'.$studlyPl;
        $serviceFqn = 'App\\Services\\'.$service;

        $pk = $this->resolvePk($meta);
        $formCols = $this->formColumns($meta);
        $tableCols = $this->tableColumns($meta, $pk);
        $showCols = $this->showColumns($meta);

        $modelFqn = trim($options->getNamespace(), '\\').'\\'.$model;
        $searchable = $this->searchableColumns($meta);
        $sortable = $tableCols;                              // every visible column is sortable
        $defaultSort = $this->defaultSortColumn($meta, $pk, $tableCols);

        $ctx = compact('model', 'slug', 'var', 'pluralVar', 'title', 'titlePl', 'service', 'lwNamespace', 'serviceFqn', 'pk', 'modelFqn', 'defaultSort');

        $classDir = app_path('Livewire/'.$studlyPl);
        $viewDir = resource_path('views/livewire/'.$slug);

        $files = [
            [$classDir.'/Index.php',                 $this->indexComponent($ctx, $searchable, $sortable)],
            [$viewDir.'/index.blade.php',            $this->indexView($ctx, $tableCols, $searchable)],
            [$classDir.'/Form.php',                  $this->formComponent($ctx, $meta, $formCols)],
            [$viewDir.'/form.blade.php',             $this->formView($ctx, $formCols)],
            [$classDir.'/Show.php',                  $this->showComponent($ctx)],
            [$viewDir.'/show.blade.php',             $this->showView($ctx, $showCols)],
        ];

        $results = [];
        foreach ($files as [$path, $content]) {
            $name = basename($path);

            if (file_exists($path) && ! $options->force) {
                $results[] = $this->result($name, $path, 'skipped', 'already exists');

                continue;
            }

            if (! $options->dryRun) {
                $dir = dirname($path);
                if (! is_dir($dir)) {
                    mkdir($dir, 0755, true);
                }
                file_put_contents($path, $content);
            }

            $results[] = $this->result($name, $path, 'success');
        }

        return $results;
    }

    // -----------------------------------------------------------------------
    // Index component
    // -----------------------------------------------------------------------

    protected function indexComponent(array $c, array $searchable, array $sortable): string
    {
        $searchArr = $this->phpStringList($searchable);
        $sortArr = $this->phpStringList($sortable);

        return <<<PHP
                    <?php

                    namespace {$c['lwNamespace']};

                    use {$c['modelFqn']};
                    use {$c['serviceFqn']};
                    use Illuminate\\Contracts\\View\\View;
                    use Illuminate\\Database\\Eloquent\\Builder;
                    use Livewire\\Attributes\\Url;
                    use Livewire\\Component;
                    use Livewire\\WithPagination;

                    class Index extends Component
                    {
                        use WithPagination;

                        #[Url(history: true, keep: true)]
                        public string \$search = '';

                        #[Url]
                        public string \$sortField = '{$c['defaultSort']}';

                        #[Url]
                        public string \$sortDirection = 'desc';

                        #[Url]
                        public int \$perPage = 15;

                        /** Columns scanned by the global search box (text columns). */
                        protected array \$searchable = {$searchArr};

                        /** Columns the user is allowed to sort by (whitelist — prevents SQL injection via the URL). */
                        protected array \$sortable = {$sortArr};

                        protected function service(): {$c['service']}
                        {
                            return app({$c['service']}::class);
                        }

                        public function updatingSearch(): void
                        {
                            \$this->resetPage();
                        }

                        public function updatingPerPage(): void
                        {
                            \$this->resetPage();
                        }

                        public function clearSearch(): void
                        {
                            \$this->search = '';
                            \$this->resetPage();
                        }

                        public function sortBy(string \$field): void
                        {
                            if (! in_array(\$field, \$this->sortable, true)) {
                                return;
                            }

                            if (\$this->sortField === \$field) {
                                \$this->sortDirection = \$this->sortDirection === 'asc' ? 'desc' : 'asc';
                            } else {
                                \$this->sortField = \$field;
                                \$this->sortDirection = 'asc';
                            }

                            \$this->resetPage();
                        }

                        public function delete(int|string \$id): void
                        {
                            \$this->service()->delete(\$id);

                            session()->flash('success', '{$c['title']} deleted.');

                            \$this->resetPage();
                        }

                        /**
                         * Build the listing query: global search across text columns + whitelisted sort.
                         * Reads go straight to the model; writes (delete) still flow through the service.
                         */
                        protected function rows(): Builder
                        {
                            \$driver = {$c['model']}::query()->getConnection()->getDriverName();
                            \$like   = \$driver === 'pgsql' ? 'ilike' : 'like';

                            return {$c['model']}::query()
                                ->when(\$this->search !== '' && \$this->searchable !== [], function (Builder \$query) use (\$like) {
                                    \$term = '%'.addcslashes(trim(\$this->search), '%_\\\\').'%';

                                    \$query->where(function (Builder \$sub) use (\$like, \$term) {
                                        foreach (\$this->searchable as \$column) {
                                            \$sub->orWhere(\$column, \$like, \$term);
                                        }
                                    });
                                })
                                ->when(
                                    in_array(\$this->sortField, \$this->sortable, true),
                                    fn (Builder \$query) => \$query->orderBy(\$this->sortField, \$this->sortDirection === 'asc' ? 'asc' : 'desc'),
                                );
                        }

                        public function render(): View
                        {
                            return view('livewire.{$c['slug']}.index', [
                                '{$c['pluralVar']}' => \$this->rows()->paginate(\$this->perPage),
                                'searchable'        => \$this->searchable,
                            ]);
                        }
                    }

                    PHP;
    }

    protected function indexView(array $c, array $tableCols, array $searchable): string
    {
        // Sortable column headers — first two columns always visible, the rest
        // collapse on small screens to keep the table readable on mobile.
        $head = '';
        $row = '';
        foreach (array_values($tableCols) as $i => $col) {
            $label = $this->label($col);
            $hide = $i >= 2 ? ' hidden lg:table-cell' : '';
            $arrow = "@if (\$sortField === '{$col}')<span class=\"ml-1 text-brand-600\">{!! \$sortDirection === 'asc' ? '&uarr;' : '&darr;' !!}</span>@endif";

            $head .= <<<HEAD
                        <th class="table-th{$hide}">
                            <button type="button" wire:click="sortBy('{$col}')" class="group inline-flex items-center gap-1 hover:text-gray-700">
                                {$label}
                                {$arrow}
                            </button>
                        </th>

                    HEAD;
            $row .= "<td class=\"table-td{$hide}\">{{ \\Illuminate\\Support\\Str::limit((string) \$%VAR%->{$col}, 60) }}</td>\n";
        }

        $colspan = count($tableCols) + 1;
        $hasSearch = $searchable !== [];

        $searchBox = $hasSearch ? <<<'SEARCH'
            <div class="relative w-full sm:w-72">
                <span class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3 text-gray-400">
                    <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-4.35-4.35M17 11a6 6 0 11-12 0 6 6 0 0112 0z"/></svg>
                </span>
                <input type="search" wire:model.live.debounce.300ms="search"
                       placeholder="Search %TITLE_PLURAL%…"
                       class="form-input pl-9 pr-9">
                        @if($search !== '')
                    <button type="button" wire:click="clearSearch"
                            class="absolute inset-y-0 right-0 flex items-center pr-3 text-gray-400 hover:text-gray-600" aria-label="Clear search">
                        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/></svg>
                    </button>
                @endif
            </div>
            SEARCH : '';

        $tpl = <<<'BLADE'
                    <div>
                        @section('title', '%TITLE_PLURAL%')

                    {{-- Header --}}
                        <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                        <div>
                            <h2 class="text-2xl font-bold text-gray-900">%TITLE_PLURAL%</h2>
                            <p class="mt-0.5 text-sm text-gray-500">{{ $%PLURAL_VAR%->total() }} {{ \Illuminate\Support\Str::plural('record', $%PLURAL_VAR%->total()) }}</p>
                        </div>
                        <a href="{{ route('%SLUG%.create') }}" class="btn-primary self-start sm:self-auto">
                            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4"/></svg>
                            New %TITLE%
                        </a>
                    </div>

                    {{-- Toolbar --}}
                    <div class="card mb-4">
                        <div class="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between">
                                %SEARCH_BOX%
                            <div class="flex items-center gap-2 text-sm text-gray-500">
                                <span>Per page</span>
                                <select wire:model.live="perPage" class="form-select w-auto py-1.5">
                                    <option value="10">10</option>
                                    <option value="15">15</option>
                                    <option value="25">25</option>
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                </select>
                            </div>
                        </div>

                        {{-- Table --}}
                        <div class="relative overflow-x-auto border-t border-gray-200">
                            {{-- Loading veil --}}
                            <div wire:loading.delay.flex wire:target="search,sortBy,perPage,nextPage,previousPage,gotoPage"
                                class="absolute inset-0 z-10 hidden items-center justify-center bg-white/60 backdrop-blur-sm">
                                <svg class="h-6 w-6 animate-spin text-brand-600" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"/></svg>
                            </div>

                            <table class="min-w-full divide-y divide-gray-200">
                                <thead class="bg-gray-50">
                                    <tr>
                                    %TABLE_HEAD%<th class="table-th text-right">Actions</th>
                                    </tr>
                                </thead>
                                <tbody class="divide-y divide-gray-100">
                                    @forelse($%PLURAL_VAR% as $%VAR%)
                                        <tr wire:key="%SLUG%-{{ $%VAR%->getKey() }}" class="odd:bg-white even:bg-gray-50/50 hover:bg-brand-50/40">
                                            %TABLE_ROW% <td class="table-td text-right whitespace-nowrap">
                                                <div class="flex items-center justify-end gap-1">
                                                    <a href="{{ route('%SLUG%.show', $%VAR%) }}" class="icon-btn" title="View">
                                                        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
                                                    </a>
                                                    <a href="{{ route('%SLUG%.edit', $%VAR%) }}" class="icon-btn" title="Edit">
                                                        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
                                                    </a>
                                                    <button type="button" class="icon-btn icon-btn-danger" title="Delete"
                                                            wire:click="delete('{{ $%VAR%->getKey() }}')"
                                                            wire:confirm="Delete this %TITLE%? This cannot be undone.">
                                                        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td colspan="%COLSPAN%" class="px-4 py-16 text-center">
                                                <div class="mx-auto flex max-w-sm flex-col items-center">
                                                    <div class="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-gray-100 text-gray-400">
                                                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5"><path stroke-linecap="round" stroke-linejoin="round" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"/></svg>
                                                    </div>
                                                    <p class="font-medium text-gray-700">No %TITLE_PLURAL% found</p>
                                                    <p class="mt-1 text-sm text-gray-500">
                                                        @if($search !== '')
                                                            No results for &ldquo;{{ $search }}&rdquo;. <button type="button" wire:click="clearSearch" class="link">Clear search</button>
                                                            @else
                                                            Get started by creating a new %TITLE%.
                                                            @endif
                                                    </p>
                                                </div>
                                            </td>
                                        </tr>
                                        @endforelse
                                </tbody>
                            </table>
                        </div>

                        {{-- Footer: summary + pagination --}}
                        @if($%PLURAL_VAR%->hasPages() || $%PLURAL_VAR%->total() > 0)
                            <div class="flex flex-col gap-3 border-t border-gray-200 px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
                                <p class="text-sm text-gray-500">
                                    Showing <span class="font-medium text-gray-700">{{ $%PLURAL_VAR%->firstItem() ?? 0 }}</span>
                                    to <span class="font-medium text-gray-700">{{ $%PLURAL_VAR%->lastItem() ?? 0 }}</span>
                                    of <span class="font-medium text-gray-700">{{ $%PLURAL_VAR%->total() }}</span>
                                </p>
                                <div>{{ $%PLURAL_VAR%->onEachSide(1)->links() }}</div>
                            </div>
                        @endif
                    </div>
                </div>
            BLADE;

        return $this->apply(
            $tpl,
            [
                '%TABLE_HEAD%' => $head,
                '%TABLE_ROW%' => $row,
                '%SEARCH_BOX%' => $searchBox,
                '%COLSPAN%' => (string) $colspan,
            ] + $this->tokens($c),
        );
    }

    // -----------------------------------------------------------------------
    // Form component (create + update)
    // -----------------------------------------------------------------------

    protected function formComponent(array $c, ModelMetadata $meta, array $formCols): string
    {
        $props = '';
        $fillLines = '';
        $rules = '';

        foreach ($formCols as $col) {
            $name = $col['name'];
            $default = $this->propDefault($col);
            $props .= "    public {$this->propType($col)} \${$name} = {$default};\n";
            $fillLines .= "            \$this->{$name} = \$record->{$name};\n";
            $rules .= "            '{$name}' => ".$this->ruleArray($col).",\n";
        }

        $props = rtrim($props, "\n");
        $fillLines = rtrim($fillLines, "\n");
        $rules = rtrim($rules, "\n");

        return <<<PHP
            <?php

            namespace {$c['lwNamespace']};

            use {$c['serviceFqn']};
            use Illuminate\\Contracts\\View\\View;
            use Livewire\\Component;

            class Form extends Component
            {
                public int|string|null \$recordId;

                public bool \$editing = false;

                    {$props}

                protected function service(): {$c['service']}
                {
                    return app({$c['service']}::class);
                }

                public function mount(int|string|null \$recordId = null): void
                {
                    if (\$recordId === null) {
                        return;
                    }

                    \$record = \$this->service()->findOrFail(\$recordId);

                    \$this->recordId = \$recordId;
                    \$this->editing = true;

                        {$fillLines}
                }

                protected function rules(): array
                {
                    return [
                            {$rules}
                    ];
                }

                public function save(): void
                {
                    \$data = \$this->validate();

                    if (\$this->editing) {
                        \$this->service()->update(\$this->recordId, \$data);
                        \$message = '{$c['title']} updated.';
                    } else {
                        \$this->service()->create(\$data);
                        \$message = '{$c['title']} created.';
                    }

                    session()->flash('success', \$message);

                    \$this->redirectRoute('{$c['slug']}.index', navigate: true);
                }

                public function render(): View
                {
                    return view('livewire.{$c['slug']}.form');
                }
            }

            PHP;
    }

    protected function formView(array $c, array $formCols): string
    {
        $fields = '';
        foreach ($formCols as $col) {
            $fields .= $this->formField($col);
        }

        $tpl = <<<'BLADE'
                    <div>
                @section('title', ($editing ? 'Edit ' : 'New ') . '%TITLE%')

                    <div class="mb-6">
                        <a href="{{ route('%SLUG%.index') }}" class="inline-flex items-center gap-1 text-sm text-gray-500 hover:text-gray-700" wire:navigate>
                            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7"/></svg>
                            Back to %TITLE_PLURAL%
                        </a>
                        <h2 class="mt-2 text-2xl font-bold text-gray-900">{{ $editing ? 'Edit %TITLE%' : 'New %TITLE%' }}</h2>
                    </div>

                    <form wire:submit="save" class="card mx-auto max-w-2xl p-6">
                        <div class="grid grid-cols-1 gap-x-6 gap-y-1 sm:grid-cols-2">
                                %FORM_FIELDS%
                        </div>
                        <div class="mt-6 flex items-center justify-end gap-3 border-t border-gray-200 pt-5">
                            <a href="{{ route('%SLUG%.index') }}" class="btn-secondary" wire:navigate>Cancel</a>
                            <button type="submit" class="btn-primary" wire:loading.attr="disabled" wire:target="save">
                                <span wire:loading.remove wire:target="save">{{ $editing ? 'Save changes' : 'Create %TITLE%' }}</span>
                                <span wire:loading.flex wire:target="save" class="items-center gap-2">
                                    <svg class="h-4 w-4 animate-spin" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"/></svg>
                                    Saving…
                                </span>
                            </button>
                        </div>
                    </form>
                </div>
                BLADE;

        return $this->apply($tpl, ['%FORM_FIELDS%' => rtrim($fields, "\n")] + $this->tokens($c));
    }

    // -----------------------------------------------------------------------
    // Show component
    // -----------------------------------------------------------------------

    protected function showComponent(array $c): string
    {
        return <<<PHP
                    <?php

                    namespace {$c['lwNamespace']};

                    use {$c['serviceFqn']};
                    use Illuminate\\Contracts\\View\\View;
                    use Livewire\\Component;

                    class Show extends Component
                    {
                        public int|string \$recordId;

                        public function mount(int|string \$recordId): void
                        {
                            \$this->recordId = \$recordId;
                        }

                        protected function service(): {$c['service']}
                        {
                            return app({$c['service']}::class);
                        }

                        public function render(): View
                        {
                            return view('livewire.{$c['slug']}.show', [
                                '{$c['var']}' => \$this->service()->findOrFail(\$this->recordId),
                            ]);
                        }
                    }

                    PHP;
    }

    protected function showView(array $c, array $showCols): string
    {
        $rows = '';
        foreach ($showCols as $col) {
            $label = $this->label($col);
            $rows .= "<div class=\"px-6 py-4\">\n"
                ."   <dt class=\"text-xs font-medium uppercase tracking-wider text-gray-500\">{$label}</dt>\n"
                ."   <dd class=\"mt-1 text-sm text-gray-900 break-words\">{{ \$%VAR%->{$col} ?? '—' }}</dd>\n"
                ."   </div>\n";
        }

        $tpl = <<<'BLADE'
                    <div>
                    @section('title', '%TITLE%')
                        <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                            <div>
                                <a href="{{ route('%SLUG%.index') }}" class="inline-flex items-center gap-1 text-sm text-gray-500 hover:text-gray-700" wire:navigate>
                                    <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7"/></svg>
                                    Back to %TITLE_PLURAL%
                                </a>
                                <h2 class="mt-2 text-2xl font-bold text-gray-900">%TITLE% details</h2>
                            </div>
                            <a href="{{ route('%SLUG%.edit', $%VAR%) }}" class="btn-primary self-start sm:self-auto" wire:navigate>
                                <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
                                Edit
                            </a>
                        </div>
                        <div class="card overflow-hidden">
                            <dl class="grid grid-cols-1 divide-y divide-gray-100 sm:grid-cols-2 sm:divide-y-0 sm:[&>div]:border-b sm:[&>div]:border-gray-100">
                                    %SHOW_ROWS%        
                            </dl>
                        </div>
                    </div>
                    BLADE;

        return $this->apply($tpl, ['%SHOW_ROWS%' => $rows] + $this->tokens($c));
    }

    // -----------------------------------------------------------------------
    // Field rendering (wire:model inputs)
    // -----------------------------------------------------------------------

    protected function formField(array $col): string
    {
        $name = $col['name'];
        $label = $this->label($name);
        $type = $this->inputType($col);
        $full = '';

        if ($type === 'textarea') {
            $control = "<textarea wire:model=\"{$name}\" rows=\"4\" class=\"form-textarea\"></textarea>";
            $full = ' sm:col-span-2';
        } elseif ($type === 'checkbox') {
            return " <div class=\"mb-4 flex items-center gap-2 sm:col-span-2\">\n"
                ."  <input type=\"checkbox\" wire:model=\"{$name}\" id=\"{$name}\" class=\"h-4 w-4 rounded border-gray-300 text-brand-600 focus:ring-brand-500\">\n"
                ."  <label for=\"{$name}\" class=\"text-sm font-medium text-gray-700\">{$label}</label>\n"
                ."   @error('{$name}') <p class=\"text-sm text-red-600\">{{ \$message }}</p> @enderror\n"
                ."  </div>\n";
        } elseif ($type === 'select') {
            $options = '';
            foreach ($this->enumValues($col) as $opt) {
                $options .= "\n 
                <option value=\"{$opt}\">{$opt}</option>";
            }
            $control = "<select wire:model=\"{$name}\" class=\"form-select\">\n"
                ."<option value=\"\">&mdash; Select &mdash;</option>{$options}\n                </select>";
        } else {
            $step = $type === 'number' && $this->isDecimal($col) ? ' step="any"' : '';
            $control = "<input type=\"{$type}\" wire:model=\"{$name}\"{$step} class=\"form-input\">";
        }

        return " <div class=\"mb-4{$full}\">\n"
            ." <label class=\"form-label\">{$label}</label>\n"
            ." {$control}\n"
            ." @error('{$name}') <p class=\"mt-1 text-sm text-red-600\">{{ \$message }}</p> @enderror\n"
            ." </div>\n";
    }

    // -----------------------------------------------------------------------
    // Validation rules + PHP property typing (derived from columns)
    // -----------------------------------------------------------------------

    protected function ruleArray(array $col): string
    {
        $rules = [];
        $rules[] = ($col['nullable'] ?? false) ? "'nullable'" : "'required'";

        $type = $this->inputType($col);
        $raw = strtolower(preg_replace('/\(.*\)/', '', $col['type'] ?? 'varchar'));

        if ($type === 'checkbox') {
            $rules = ["'boolean'"];
        } elseif ($type === 'number') {
            $rules[] = $this->isDecimal($col) ? "'numeric'" : "'integer'";
        } elseif (in_array($type, ['date', 'datetime-local'], true)) {
            $rules[] = "'date'";
        } elseif ($type === 'email') {
            $rules[] = "'email'";
        } elseif ($type === 'url') {
            $rules[] = "'url'";
        } elseif (in_array($raw, ['varchar', 'char', 'string'], true)) {
            $rules[] = "'string'";
            if (! empty($col['length'])) {
                $rules[] = "'max:".((int) $col['length'])."'";
            } else {
                $rules[] = "'max:255'";
            }
        } elseif ($type === 'textarea') {
            $rules[] = "'string'";
        }

        return '['.implode(', ', $rules).']';
    }

    protected function propType(array $col): string
    {
        $type = $this->inputType($col);
        $nullable = ($col['nullable'] ?? false) ? '?' : '';

        return match ($type) {
            'checkbox' => 'bool',
            'number' => $this->isDecimal($col) ? "{$nullable}float" : "{$nullable}int",
            default => "{$nullable}string",
        };
    }

    protected function propDefault(array $col): string
    {
        $type = $this->inputType($col);

        if ($type === 'checkbox') {
            return 'false';
        }
        if (($col['nullable'] ?? false)) {
            return 'null';
        }

        return match ($type) {
            'number' => 'null',
            default => "''",
        };
    }

    // -----------------------------------------------------------------------
    // Column selection / type inference (mirrors ViewGenerator)
    // -----------------------------------------------------------------------

    protected function formColumns(ModelMetadata $meta): array
    {
        $skip = array_merge(
            [$meta->primaryKey, 'created_at', 'updated_at', 'deleted_at', 'remember_token', 'password', 'email_verified_at'],
            $meta->compositePrimaryKey ?? [],
        );

        return array_values(array_filter(
            $meta->columns,
            fn ($c): bool => ! in_array($c['name'], $skip, true) && ! in_array($c['name'], self::SENSITIVE, true),
        ));
    }

    protected function tableColumns(ModelMetadata $meta, ?string $pk): array
    {
        $skip = ['deleted_at', 'updated_at'];
        $names = [];

        if ($pk !== null) {
            $names[] = $pk;
        }

        foreach ($meta->columns as $c) {
            if (count($names) >= 5) {
                break;
            }
            $n = $c['name'];
            if ($n === $pk || in_array($n, self::SENSITIVE, true) || in_array($n, $skip, true)) {
                continue;
            }
            if ($this->inputType($c) === 'textarea') {
                continue;
            }
            $names[] = $n;
        }

        if (empty($names) && ! empty($meta->columns)) {
            $names[] = $meta->columns[0]['name'];
        }

        return $names;
    }

    /**
     * Text-ish columns the global search box scans. Excludes sensitive fields,
     * timestamps, and the primary key (searching a PK as text is rarely useful).
     *
     * @return list<string>
     */
    protected function searchableColumns(ModelMetadata $meta): array
    {
        $skip = ['created_at', 'updated_at', 'deleted_at', $meta->primaryKey];
        $names = [];

        foreach ($meta->columns as $c) {
            $name = $c['name'];
            if (in_array($name, $skip, true) || in_array($name, self::SENSITIVE, true)) {
                continue;
            }

            $raw = strtolower(preg_replace('/\(.*\)/', '', $c['type'] ?? ''));
            $isText = in_array($raw, [
                'char',
                'character',
                'varchar',
                'character varying',
                'string',
                'text',
                'tinytext',
                'mediumtext',
                'longtext',
                'citext',
                'clob',
                'nchar',
                'nvarchar',
            ], true);

            if ($isText) {
                $names[] = $name;
            }
        }

        return $names;
    }

    /**
     * Default sort column: created_at if present, otherwise the primary key,
     * otherwise the first visible table column.
     */
    protected function defaultSortColumn(ModelMetadata $meta, ?string $pk, array $tableCols): string
    {
        $columns = array_column($meta->columns, 'name');

        if (in_array('created_at', $columns, true)) {
            return 'created_at';
        }

        if ($pk !== null) {
            return $pk;
        }

        return $tableCols[0] ?? ($columns[0] ?? 'id');
    }

    /**
     * Render a list of strings as a PHP array literal: ['a', 'b', 'c'].
     */
    protected function phpStringList(array $items): string
    {
        if ($items === []) {
            return '[]';
        }

        return '['.implode(', ', array_map(fn ($i): string => "'".addslashes((string) $i)."'", $items)).']';
    }

    protected function showColumns(ModelMetadata $meta): array
    {
        return array_values(array_filter(
            array_column($meta->columns, 'name'),
            fn ($n): bool => ! in_array($n, self::SENSITIVE, true),
        ));
    }

    protected function resolvePk(ModelMetadata $meta): ?string
    {
        $columns = array_column($meta->columns, 'name');

        $candidates = array_merge([$meta->primaryKey], $meta->compositePrimaryKey ?? [], ['id']);
        foreach ($candidates as $cand) {
            if (is_string($cand) && $cand !== '' && in_array($cand, $columns, true)) {
                return $cand;
            }
        }

        return $columns[0] ?? null;
    }

    protected function inputType(array $col): string
    {
        $name = strtolower((string) $col['name']);
        $raw = strtolower($col['type'] ?? 'varchar');
        $type = preg_replace('/\(.*\)/', '', $raw);

        if (str_starts_with($raw, 'enum')) {
            return 'select';
        }
        if ($type === 'tinyint' && str_contains($raw, '(1)')) {
            return 'checkbox';
        }
        if (in_array($type, ['boolean', 'bool'], true)) {
            return 'checkbox';
        }
        if (in_array($type, ['text', 'mediumtext', 'longtext', 'tinytext', 'json', 'jsonb'], true)) {
            return 'textarea';
        }
        if (in_array($type, ['int', 'integer', 'bigint', 'smallint', 'mediumint', 'decimal', 'numeric', 'float', 'double', 'real'], true)) {
            return 'number';
        }
        if ($type === 'date') {
            return 'date';
        }
        if (in_array($type, ['datetime', 'timestamp'], true)) {
            return 'datetime-local';
        }
        if (str_contains($name, 'email')) {
            return 'email';
        }
        if (str_contains($name, 'url') || str_contains($name, 'website')) {
            return 'url';
        }

        return 'text';
    }

    protected function isDecimal(array $col): bool
    {
        $type = strtolower(preg_replace('/\(.*\)/', '', $col['type'] ?? ''));

        return in_array($type, ['decimal', 'numeric', 'float', 'double', 'real'], true);
    }

    /** @return list<string> */
    protected function enumValues(array $col): array
    {
        if (preg_match("/enum\\('(.+?)'\\)/i", $col['type'] ?? '', $m)) {
            return array_map(trim(...), explode("','", $m[1]));
        }

        return [];
    }

    protected function label(string $name): string
    {
        return Str::headline(preg_replace('/_id$/', '', $name));
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /** Simple-token map shared by all view templates. */
    protected function tokens(array $c): array
    {
        return [
            '%TITLE%' => $c['title'],
            '%TITLE_PLURAL%' => $c['titlePl'],
            '%SLUG%' => $c['slug'],
            '%VAR%' => $c['var'],
            '%PLURAL_VAR%' => $c['pluralVar'],
        ];
    }

    protected function apply(string $template, array $map): string
    {
        return str_replace(array_keys($map), array_values($map), $template);
    }

    protected function result(string $name, string $path, string $status, ?string $reason = null): array
    {
        $out = ['type' => $this->getName(), 'name' => $name, 'path' => $path, 'status' => $status];
        if ($reason !== null) {
            $out['reason'] = $reason;
        }

        return $out;
    }
}
