<?php

namespace Zuqongtech\LaravelAnvil\Generators;

use Illuminate\Support\Str;
use Zuqongtech\LaravelAnvil\Contracts\Generator;
use Zuqongtech\LaravelAnvil\Support\GenerationOptions;
use Zuqongtech\LaravelAnvil\Support\Helpers;
use Zuqongtech\LaravelAnvil\Support\ModelMetadata;

/**
 * Generates boilerplate Blade views for the web scaffold (--web).
 *
 * Per model, under resources/views/{slug}/  (slug = kebab-plural, e.g. "vehicle-categories"):
 *   index.blade.php   — paginated table with View / Edit / Delete actions + "New" button
 *   create.blade.php  — create form (includes _form)
 *   edit.blade.php    — edit form (includes _form)
 *   show.blade.php     — read-only detail view
 *   _form.blade.php    — shared form fields, inferred from column types
 *
 * Once per run (idempotent, skipped if present):
 *   resources/views/layouts/anvil.blade.php  — Tailwind-CDN base layout with
 *   flash messages and validation-error display.
 *
 * Blade content is produced from nowdoc templates with %TOKEN% placeholders so
 * that PHP never interpolates Blade's own $variables / {{}} / @directives.
 */
final class ViewGenerator implements Generator
{
    public function supports(GenerationOptions $options): bool
    {
        return $options->web ?? false;
    }

    public function getName(): string
    {
        return 'View';
    }

    public function generate(ModelMetadata $meta, GenerationOptions $options): array
    {
        $results = [];

        $results[] = $this->ensureLayout($options);
        $results[] = $this->ensureNav($options);

        $slug = Helpers::modelToRouteName($meta->model);          // vehicle-categories
        $var = lcfirst($meta->model);                            // vehicleCategory
        $pluralVar = lcfirst(Str::pluralStudly($meta->model));         // vehicleCategories
        $title = Str::headline($meta->model);                      // Vehicle Category
        $titlePl = Str::headline(Str::pluralStudly($meta->model));   // Vehicle Categories
        $layout = config('anvil.web.layout', 'layouts.anvil');
        $pk = $this->resolvePk($meta);

        $dir = resource_path('views/'.$slug);

        $formCols = $this->formColumns($meta);
        $tableCols = $this->tableColumns($meta, $pk);
        $showCols = $this->showColumns($meta);

        $base = [
            '%LAYOUT%' => $layout,
            '%MODEL%' => $meta->model,
            '%TITLE%' => $title,
            '%TITLE_PLURAL%' => $titlePl,
            '%SLUG%' => $slug,
            '%VAR%' => $var,
            '%PLURAL_VAR%' => $pluralVar,
            '%PK%' => $pk ?? '',
        ];

        if ($options->isLivewire()) {
            // Livewire stack: thin wrapper views that mount the components.
            // The actual table/form/detail markup lives in the Livewire views
            // (generated by LivewireComponentGenerator); no _form partial here.
            $files = [
                'index.blade.php' => $this->renderLivewireWrapper($base, 'index'),
                'create.blade.php' => $this->renderLivewireWrapper($base, 'create'),
                'edit.blade.php' => $this->renderLivewireWrapper($base, 'edit'),
                'show.blade.php' => $this->renderLivewireWrapper($base, 'show'),
            ];
        } else {
            $files = [
                'index.blade.php' => $this->renderIndex($base, $tableCols),
                'create.blade.php' => $this->renderCreate($base),
                'edit.blade.php' => $this->renderEdit($base),
                'show.blade.php' => $this->renderShow($base, $showCols, $pk),
                '_form.blade.php' => $this->renderForm($base, $formCols, $var),
            ];
        }

        foreach ($files as $name => $content) {
            $path = "{$dir}/{$name}";

            if (file_exists($path) && ! $options->force) {
                $results[] = $this->result($name, $path, 'skipped', 'already exists');

                continue;
            }

            if (! $options->dryRun) {
                if (! is_dir($dir)) {
                    mkdir($dir, 0755, true);
                }
                file_put_contents($path, $content);
            }

            $results[] = $this->result($name, $path, 'success');
        }

        return $results;
    }

    // -----------------------------------------------------------------------
    // Layout (once)
    // -----------------------------------------------------------------------

    protected function ensureLayout(GenerationOptions $options): array
    {
        $layout = config('anvil.web.layout', 'layouts.anvil');
        $path = resource_path('views/'.str_replace('.', '/', $layout).'.blade.php');

        if (! config('anvil.web.generate_layout', true) || file_exists($path)) {
            return $this->result(basename($path), $path, 'skipped', 'layout exists or disabled');
        }

        if (! $options->dryRun) {
            $dir = dirname($path);
            if (! is_dir($dir)) {
                mkdir($dir, 0755, true);
            }
            file_put_contents($path, $this->layoutTemplate());
        }

        return $this->result(basename($path), $path, 'success', 'layout created');
    }

    protected function layoutTemplate(): string
    {
        return <<<'BLADE'
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', config('app.name', 'Laravel'))</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    fontFamily: { sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'] },
                    colors: {
                        brand: {
                            50: '#eef2ff', 100: '#e0e7ff', 200: '#c7d2fe', 300: '#a5b4fc',
                            400: '#818cf8', 500: '#6366f1', 600: '#4f46e5', 700: '#4338ca',
                            800: '#3730a3', 900: '#312e81',
                        },
                    },
                },
            },
        };
    </script>
    <style type="text/tailwindcss">
@layerbase{
            body { @apply antialiased; }
        }
@layercomponents{
            .card { @apply bg-white rounded-xl border border-gray-200 shadow-sm; }

            .form-label { @apply block text-sm font-medium text-gray-700 mb-1.5; }
            .form-input,
            .form-select,
            .form-textarea { @apply w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 shadow-sm transition placeholder:text-gray-400 focus:border-brand-500 focus:ring-2 focus:ring-brand-500/30 focus:outline-none; }

            .btn { @apply inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50; }
            .btn-primary { @apply btn bg-brand-600 text-white hover:bg-brand-700 focus:ring-brand-500; }
            .btn-secondary { @apply btn border border-gray-300 bg-white text-gray-700 hover:bg-gray-50 focus:ring-gray-400; }
            .btn-danger { @apply btn bg-red-600 text-white hover:bg-red-700 focus:ring-red-500; }
            .btn-sm { @apply px-3 py-1.5 text-xs; }

            .icon-btn { @apply inline-flex h-8 w-8 items-center justify-center rounded-lg text-gray-500 transition hover:bg-gray-100 hover:text-gray-700 focus:outline-none focus:ring-2 focus:ring-brand-500/30; }
            .icon-btn-danger { @apply hover:bg-red-50 hover:text-red-600; }

            .badge { @apply inline-flex items-center rounded-full bg-gray-100 px-2.5 py-0.5 text-xs font-medium text-gray-700; }

            .table-th { @apply px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-gray-500; }
            .table-td { @apply px-4 py-3 text-sm text-gray-700; }

            .alert { @apply flex items-start gap-3 rounded-lg border px-4 py-3 text-sm; }
            .link { @apply font-medium text-brand-600 hover:text-brand-800; }
            .link-danger { @apply cursor-pointer border-0 bg-transparent font-medium text-red-600 hover:text-red-800; }
        }
    </style>
</head>
<body class="h-full bg-gray-50 font-sans text-gray-800">
    {{-- Collapsible sidebar (links discovered at runtime) --}}
@include('layouts._anvil-nav')

    {{-- Main column — padding shifts to make room for the sidebar on desktop --}}
    <div id="anvil-main" class="flex min-h-full flex-col transition-[padding] duration-300 ease-in-out lg:pl-64">
        {{-- Top bar with the sidebar toggle --}}
        <header class="sticky top-0 z-30 border-b border-gray-200 bg-white/90 backdrop-blur">
            <div class="flex h-16 items-center gap-3 px-4 sm:px-6">
                <button type="button" data-anvil-toggle class="icon-btn lg:hidden" aria-label="Toggle navigation">
                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
                    </svg>
                </button>
                <h1 class="truncate text-base font-semibold text-gray-800">@yield('title', config('app.name', 'Laravel'))</h1>
            </div>
        </header>

        <main class="flex-1">
            <div class="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 sm:py-8">
@if(session('success'))
                    <div class="alert mb-6 border-green-200 bg-green-50 text-green-800">
                        <svg class="mt-0.5 h-5 w-5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                        <span>{{ session('success') }}</span>
                    </div>
@endif

@if(session('error'))
                    <div class="alert mb-6 border-red-200 bg-red-50 text-red-800">
                        <svg class="mt-0.5 h-5 w-5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                        <span>{{ session('error') }}</span>
                    </div>
@endif

@if($errors->any())
                    <div class="alert mb-6 border-red-200 bg-red-50 text-red-800">
                        <svg class="mt-0.5 h-5 w-5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                        <div>
                            <p class="font-semibold">Please fix the following:</p>
                            <ul class="mt-1 list-inside list-disc">
@foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
@endforeach
                            </ul>
                        </div>
                    </div>
@endif

@yield('content')
            </div>
        </main>
    </div>
</body>
</html>
BLADE;
    }

    // -----------------------------------------------------------------------
    // Navigation partial (once) — resources discovered at runtime
    // -----------------------------------------------------------------------

    /**
     * Write resources/views/layouts/_anvil-nav.blade.php once.
     *
     * The partial builds its links at render time by scanning named routes that
     * end in ".index" whose controller lives in App\Http\Controllers\Web\, so it
     * lists every web-scaffold resource automatically and stays correct as
     * resources are added or removed — no regeneration required. It is fully
     * self-contained (framework classes only; no runtime dependency on Anvil).
     */
    protected function ensureNav(GenerationOptions $options): array
    {
        $layout = config('anvil.web.layout', 'layouts.anvil');
        $layoutDir = dirname(resource_path('views/'.str_replace('.', '/', $layout).'.blade.php'));
        $path = $layoutDir.'/_anvil-nav.blade.php';

        if (! config('anvil.web.generate_nav', true)) {
            return $this->result('_anvil-nav.blade.php', $path, 'skipped', 'nav disabled');
        }

        if (file_exists($path) && ! $options->force) {
            return $this->result('_anvil-nav.blade.php', $path, 'skipped', 'already exists');
        }

        if (! $options->dryRun) {
            if (! is_dir($layoutDir)) {
                mkdir($layoutDir, 0755, true);
            }
            file_put_contents($path, $this->navTemplate());
        }

        return $this->result('_anvil-nav.blade.php', $path, 'success', 'nav created');
    }

    protected function navTemplate(): string
    {
        $namespace = addslashes(config('anvil.web.controller_namespace', 'App\\Http\\Controllers\\Web'));

        $tpl = <<<'BLADE'
@php
    /**
     * Anvil web navigation — links discovered at runtime from the registered
     * routes. Every "<resource>.index" route whose controller is in the web
     * scaffold namespace becomes a nav item. Edit freely; it is plain Blade.
     */
    $anvilNavItems = collect(app('router')->getRoutes()->getRoutesByName())
        ->filter(fn ($route, $name) => str_ends_with($name, '.index')
            && str_contains((string) $route->getActionName(), '%NAMESPACE%'))
        ->map(function ($route, $name) {
            $base = \Illuminate\Support\Str::beforeLast($name, '.index');

            return (object) [
                'name'   => $name,
                'label'  => \Illuminate\Support\Str::headline(str_replace('-', ' ', $base)),
                'url'    => route($name),
                'active' => request()->routeIs($base . '.*'),
            ];
        })
        ->sortBy('label')
        ->values();
@endphp

{{-- Backdrop (mobile only, shown when the sidebar is open) --}}
<div id="anvil-backdrop" class="fixed inset-0 z-40 bg-black/50 hidden lg:hidden"></div>

{{-- Sidebar --}}
<aside id="anvil-sidebar"
       class="fixed inset-y-0 left-0 z-50 flex w-64 flex-col bg-[#1a1a2e] text-gray-200
              transform -translate-x-full lg:translate-x-0 transition-transform duration-300 ease-in-out">
    {{-- Brand --}}
    <div class="flex h-16 shrink-0 items-center gap-2 border-b border-white/10 px-5">
        <a href="{{ url('/') }}" class="flex items-center gap-2 group">
            <span class="text-2xl leading-none">&#9874;</span>
            <span class="font-bold tracking-wide text-white group-hover:text-brand-300 transition">
                {{ config('app.name', 'Laravel') }}
            </span>
        </a>
        {{-- Close (mobile) --}}
        <button type="button" data-anvil-toggle
                class="ml-auto rounded-md p-1 text-gray-400 hover:bg-white/10 hover:text-white lg:hidden"
                aria-label="Close navigation">
            <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
        </button>
    </div>

    {{-- Links (scroll independently when there are many resources) --}}
    <nav class="flex-1 overflow-y-auto px-3 py-4 space-y-1">
        <p class="px-3 pb-2 text-[11px] font-semibold uppercase tracking-wider text-gray-500">Resources</p>
@forelse($anvilNavItems as $item)
            <a href="{{ $item->url }}" data-anvil-link
               class="group flex items-center gap-3 rounded-md px-3 py-2 text-sm font-medium transition
                      {{ $item->active
                            ? 'bg-white/10 text-white'
                            : 'text-gray-400 hover:bg-white/5 hover:text-white' }}">
                <span class="h-1.5 w-1.5 rounded-full transition
                             {{ $item->active ? 'bg-brand-400' : 'bg-gray-600 group-hover:bg-gray-400' }}"></span>
                <span class="truncate">{{ $item->label }}</span>
            </a>
@empty
            <p class="px-3 py-2 text-sm text-gray-500">No resources yet.</p>
@endforelse
    </nav>

    {{-- Footer --}}
    <div class="shrink-0 border-t border-white/10 px-5 py-3 text-xs text-gray-500">
        &#9874; Forged by Anvil
    </div>
</aside>

<script>
(function () {
    var sidebar  = document.getElementById('anvil-sidebar');
    var main     = document.getElementById('anvil-main');
    var backdrop = document.getElementById('anvil-backdrop');
    if (!sidebar || !main) { return; }

    var KEY = 'anvil-sidebar-open';
    var desktop = window.matchMedia('(min-width: 1024px)');

    function apply(open) {
        sidebar.classList.toggle('-translate-x-full', !open);
        sidebar.classList.toggle('translate-x-0', open);
        sidebar.classList.toggle('lg:-translate-x-full', !open);
        sidebar.classList.toggle('lg:translate-x-0', open);
        main.classList.toggle('lg:pl-64', open);
        main.classList.toggle('lg:pl-0', !open);
        if (backdrop) { backdrop.classList.toggle('hidden', !open); }
    }

    function setOpen(open, persist) {
        apply(open);
        if (persist && desktop.matches) {
            try { localStorage.setItem(KEY, open ? '1' : '0'); } catch (e) {}
        }
    }

    function desktopPref() {
        try { var s = localStorage.getItem(KEY); if (s !== null) { return s === '1'; } } catch (e) {}
        return true; // open by default on desktop
    }

    // Initial state: remember the choice on desktop, always closed on mobile.
    setOpen(desktop.matches ? desktopPref() : false, false);

    document.querySelectorAll('[data-anvil-toggle]').forEach(function (btn) {
        btn.addEventListener('click', function () {
            var isClosed = sidebar.classList.contains('-translate-x-full');
            setOpen(isClosed, true);
        });
    });

    if (backdrop) {
        backdrop.addEventListener('click', function () { setOpen(false, false); });
    }

    // On mobile, following a link should close the overlay.
    document.querySelectorAll('[data-anvil-link]').forEach(function (a) {
        a.addEventListener('click', function () { if (!desktop.matches) { setOpen(false, false); } });
    });

    // Re-apply the correct state when crossing the desktop breakpoint.
    desktop.addEventListener('change', function (e) {
        setOpen(e.matches ? desktopPref() : false, false);
    });
})();
</script>
BLADE;

        return str_replace('%NAMESPACE%', $namespace, $tpl);
    }
    // -----------------------------------------------------------------------

    /**
     * Thin wrapper view (Livewire stack): renders the layout and mounts the
     * matching Livewire component. Create/edit pass the record id through.
     */
    protected function renderLivewireWrapper(array $base, string $kind): string
    {
        $tag = match ($kind) {
            'create' => '<livewire:%SLUG%.form />',
            'edit' => '<livewire:%SLUG%.form :record-id="$recordId" />',
            'show' => '<livewire:%SLUG%.show :record-id="$recordId" />',
            default => '<livewire:%SLUG%.index />',
        };

        $titleToken = $kind === 'index' ? '%TITLE_PLURAL%' : '%TITLE%';
        $heading = match ($kind) {
            'create' => 'New %TITLE%',
            'edit' => 'Edit %TITLE%',
            default => $titleToken,
        };

        $tpl = <<<BLADE
@extends('%LAYOUT%')

@section('title', '{$heading}')

@section('content')
    {$tag}
@endsection
BLADE;

        return $this->apply($tpl, $base);
    }

    protected function renderIndex(array $base, array $tableCols): string
    {
        $head = '';
        $row = '';
        foreach ($tableCols as $col) {
            $label = $this->label($col);
            $head .= "                <th class=\"px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase\">{$label}</th>\n";
            $row .= "                    <td class=\"px-4 py-3 text-sm text-gray-700\">{{ \$%VAR%->{$col} }}</td>\n";
        }

        $tpl = <<<'BLADE'
@extends('%LAYOUT%')

@section('title', '%TITLE_PLURAL%')

@section('content')
    <div class="flex items-center justify-between mb-6">
        <h1 class="text-2xl font-bold">%TITLE_PLURAL%</h1>
        <a href="{{ route('%SLUG%.create') }}" class="btn-primary">+ New %TITLE%</a>
    </div>

    <div class="overflow-x-auto bg-white rounded-lg shadow">
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
                <tr>
%TABLE_HEAD%                    <th class="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Actions</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-100">
@forelse($%PLURAL_VAR% as $%VAR%)
                    <tr class="hover:bg-gray-50">
%TABLE_ROW%                        <td class="px-4 py-3 text-right whitespace-nowrap">
                            <a href="{{ route('%SLUG%.show', $%VAR%) }}" class="link">View</a>
                            <a href="{{ route('%SLUG%.edit', $%VAR%) }}" class="link">Edit</a>
                            <form action="{{ route('%SLUG%.destroy', $%VAR%) }}" method="POST" class="inline" onsubmit="return confirm('Delete this %TITLE%?')">
@csrf
@method('DELETE')
                                <button type="submit" class="link-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
@empty
                    <tr><td colspan="99" class="px-4 py-6 text-center text-gray-400">No %TITLE_PLURAL% found.</td></tr>
@endforelse
            </tbody>
        </table>
    </div>

    <div class="mt-4">
        {{ $%PLURAL_VAR%->links() }}
    </div>
@endsection
BLADE;

        return $this->apply($tpl, ['%TABLE_HEAD%' => $head, '%TABLE_ROW%' => $row] + $base);
    }

    protected function renderCreate(array $base): string
    {
        $tpl = <<<'BLADE'
@extends('%LAYOUT%')

@section('title', 'New %TITLE%')

@section('content')
    <div class="max-w-2xl mx-auto">
        <h1 class="text-2xl font-bold mb-6">New %TITLE%</h1>

        <form action="{{ route('%SLUG%.store') }}" method="POST" class="bg-white rounded-lg shadow p-6">
@csrf
@include('%SLUG%._form')

            <div class="flex items-center gap-3 mt-6">
                <button type="submit" class="btn-primary">Create</button>
                <a href="{{ route('%SLUG%.index') }}" class="btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
@endsection
BLADE;

        return $this->apply($tpl, $base);
    }

    protected function renderEdit(array $base): string
    {
        $tpl = <<<'BLADE'
@extends('%LAYOUT%')

@section('title', 'Edit %TITLE%')

@section('content')
    <div class="max-w-2xl mx-auto">
        <h1 class="text-2xl font-bold mb-6">Edit %TITLE%</h1>

        <form action="{{ route('%SLUG%.update', $%VAR%) }}" method="POST" class="bg-white rounded-lg shadow p-6">
@csrf
@method('PUT')
@include('%SLUG%._form', ['%VAR%' => $%VAR%])

            <div class="flex items-center gap-3 mt-6">
                <button type="submit" class="btn-primary">Save changes</button>
                <a href="{{ route('%SLUG%.index') }}" class="btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
@endsection
BLADE;

        return $this->apply($tpl, $base);
    }

    protected function renderShow(array $base, array $showCols, ?string $pk): string
    {
        $rows = '';
        foreach ($showCols as $col) {
            $label = $this->label($col);
            $rows .= "            <div class=\"py-3 border-b border-gray-100\">\n"
                ."                <dt class=\"text-sm font-medium text-gray-500\">{$label}</dt>\n"
                ."                <dd class=\"text-gray-900\">{{ \$%VAR%->{$col} }}</dd>\n"
                ."            </div>\n";
        }

        // Only show a "#<id>" badge when the model has a real key column,
        // otherwise printing $model->%PK% would throw under strict attributes.
        $pkBadge = $pk ? ' #{{ $%VAR%->'.$pk.' }}' : '';
        $pkBadgeTitle = $pk ? ' #{{ $%VAR%->'.$pk.' }}' : '';

        $tpl = <<<'BLADE'
@extends('%LAYOUT%')

@section('title', '%TITLE%%PK_BADGE_TITLE%')

@section('content')
    <div class="max-w-2xl mx-auto">
        <div class="flex items-center justify-between mb-6">
            <h1 class="text-2xl font-bold">%TITLE%%PK_BADGE%</h1>
            <div>
                <a href="{{ route('%SLUG%.edit', $%VAR%) }}" class="btn-primary">Edit</a>
                <a href="{{ route('%SLUG%.index') }}" class="btn-secondary">Back</a>
            </div>
        </div>

        <dl class="bg-white rounded-lg shadow p-6">
%SHOW_ROWS%        </dl>
    </div>
@endsection
BLADE;

        return $this->apply($tpl, [
            '%SHOW_ROWS%' => $rows,
            '%PK_BADGE_TITLE%' => $pkBadgeTitle,
            '%PK_BADGE%' => $pkBadge,
        ] + $base);
    }

    protected function renderForm(array $base, array $formCols, string $var): string
    {
        $fields = '';
        foreach ($formCols as $col) {
            $fields .= $this->formField($col);
        }

        // The partial only contains the field markup; %VAR% is resolved last.
        return $this->apply($fields, $base);
    }

    // -----------------------------------------------------------------------
    // Field builders (return Blade with %VAR% token, resolved by apply())
    // -----------------------------------------------------------------------

    protected function formField(array $col): string
    {
        $name = $col['name'];
        $label = $this->label($name);
        $type = $this->inputType($col);
        $req = ($col['nullable'] ?? false) ? '' : ' required';

        $valueExpr = "old('{$name}', optional(\$%VAR% ?? null)->{$name})";

        if ($type === 'textarea') {
            $control = "<textarea name=\"{$name}\" rows=\"4\" class=\"form-input\"{$req}>{{ {$valueExpr} }}</textarea>";
        } elseif ($type === 'checkbox') {
            $control = "<input type=\"hidden\" name=\"{$name}\" value=\"0\">\n"
                ."        <input type=\"checkbox\" name=\"{$name}\" value=\"1\" {{ {$valueExpr} ? 'checked' : '' }} class=\"rounded border-gray-300\">";
        } elseif ($type === 'select') {
            $options = '';
            foreach ($this->enumValues($col) as $opt) {
                $options .= "\n            <option value=\"{$opt}\" {{ {$valueExpr} === '{$opt}' ? 'selected' : '' }}>{$opt}</option>";
            }
            $control = "<select name=\"{$name}\" class=\"form-input\"{$req}>\n"
                ."            <option value=\"\">&mdash; Select &mdash;</option>{$options}\n        </select>";
        } else {
            $step = $type === 'number' && $this->isDecimal($col) ? ' step="any"' : '';
            $control = "<input type=\"{$type}\" name=\"{$name}\" value=\"{{ {$valueExpr} }}\"{$step} class=\"form-input\"{$req}>";
        }

        return "    <div class=\"mb-4\">\n"
            ."        <label class=\"block text-sm font-medium text-gray-700 mb-1\">{$label}</label>\n"
            ."        {$control}\n"
            ."        @error('{$name}') <p class=\"text-sm text-red-600 mt-1\">{{ \$message }}</p> @enderror\n"
            ."    </div>\n";
    }

    // -----------------------------------------------------------------------
    // Column selection
    // -----------------------------------------------------------------------

    /** Columns shown on create/edit forms. */
    protected function formColumns(ModelMetadata $meta): array
    {
        $skip = array_merge(
            [$meta->primaryKey, 'created_at', 'updated_at', 'deleted_at', 'remember_token', 'password', 'email_verified_at'],
            $meta->compositePrimaryKey,
        );

        return array_values(array_filter(
            array_map(fn ($c) => $c, $meta->columns),
            fn ($c) => ! in_array($c['name'], $skip, true),
        ));
    }

    /** Columns shown as table columns on index (pk + a few scalars). */
    protected function tableColumns(ModelMetadata $meta, ?string $pk): array
    {
        $sensitive = ['password', 'remember_token'];
        $skip = ['deleted_at', 'updated_at'];
        $names = [];

        // Only lead with the key column when it actually exists, so the view
        // never prints $record->id on a table that has no such attribute.
        if ($pk !== null) {
            $names[] = $pk;
        }

        foreach ($meta->columns as $c) {
            if (count($names) >= 5) {
                break;
            }
            $n = $c['name'];
            if ($n === $pk || in_array($n, $sensitive, true) || in_array($n, $skip, true)) {
                continue;
            }
            if ($this->inputType($c) === 'textarea') {
                continue; // skip long text in tables
            }
            $names[] = $n;
        }

        // Fallback: a key-less table with only skipped columns still needs at
        // least one column to render a meaningful row.
        if (empty($names) && ! empty($meta->columns)) {
            $names[] = $meta->columns[0]['name'];
        }

        return $names;
    }

    /**
     * Resolve the primary key to a column that genuinely exists on the model,
     * so generated views never reference a missing attribute (which throws under
     * Model::preventAccessingMissingAttributes()). Falls back through:
     * detected PK → first composite-PK column → "id" if present → first column →
     * null (only when the table has no columns at all).
     */
    protected function resolvePk(ModelMetadata $meta): ?string
    {
        $columns = array_column($meta->columns, 'name');

        $candidates = array_merge(
            [$meta->primaryKey],
            $meta->compositePrimaryKey ?? [],
            ['id'],
        );

        foreach ($candidates as $cand) {
            if (is_string($cand) && $cand !== '' && in_array($cand, $columns, true)) {
                return $cand;
            }
        }

        return $columns[0] ?? null;
    }

    /** Columns shown on the show page (all non-sensitive). */
    protected function showColumns(ModelMetadata $meta): array
    {
        $sensitive = ['password', 'remember_token'];

        return array_values(array_filter(
            array_column($meta->columns, 'name'),
            fn ($n) => ! in_array($n, $sensitive, true),
        ));
    }

    // -----------------------------------------------------------------------
    // Type inference
    // -----------------------------------------------------------------------

    protected function inputType(array $col): string
    {
        $name = strtolower($col['name']);
        $raw = strtolower($col['type'] ?? 'varchar');
        $type = preg_replace('/\(.*\)/', '', $raw);

        if (str_starts_with($raw, 'enum')) {
            return 'select';
        }
        if ($type === 'tinyint' && str_contains($raw, '(1)')) {
            return 'checkbox';
        }
        if (in_array($type, ['boolean', 'bool'], true)) {
            return 'checkbox';
        }
        if (in_array($type, ['text', 'mediumtext', 'longtext', 'tinytext', 'json', 'jsonb'], true)) {
            return 'textarea';
        }
        if (in_array($type, ['int', 'integer', 'bigint', 'smallint', 'mediumint', 'decimal', 'numeric', 'float', 'double', 'real'], true)) {
            return 'number';
        }
        if ($type === 'date') {
            return 'date';
        }
        if (in_array($type, ['datetime', 'timestamp'], true)) {
            return 'datetime-local';
        }
        if (str_contains($name, 'email')) {
            return 'email';
        }
        if (str_contains($name, 'password')) {
            return 'password';
        }
        if (str_contains($name, 'url') || str_contains($name, 'website')) {
            return 'url';
        }

        return 'text';
    }

    protected function isDecimal(array $col): bool
    {
        $type = strtolower(preg_replace('/\(.*\)/', '', $col['type'] ?? ''));

        return in_array($type, ['decimal', 'numeric', 'float', 'double', 'real'], true);
    }

    /** @return list<string> */
    protected function enumValues(array $col): array
    {
        if (preg_match("/enum\('(.+?)'\)/i", $col['type'] ?? '', $m)) {
            return array_map('trim', explode("','", $m[1]));
        }

        return [];
    }

    protected function label(string $name): string
    {
        return Str::headline(preg_replace('/_id$/', '', $name));
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /**
     * Sequential token replacement. Block tokens (%TABLE_ROW% etc.) must be in
     * $map before %VAR%/%SLUG% so that %VAR% inside an injected block is also
     * resolved (str_replace reprocesses prior replacements).
     */
    protected function apply(string $template, array $map): string
    {
        return str_replace(array_keys($map), array_values($map), $template);
    }

    protected function result(string $name, string $path, string $status, ?string $reason = null): array
    {
        $out = [
            'type' => $this->getName(),
            'name' => $name,
            'path' => $path,
            'status' => $status,
        ];

        if ($reason !== null) {
            $out['reason'] = $reason;
        }

        return $out;
    }
}