<?php

namespace Zuqongtech\LaravelAnvil\Http;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Symfony\Component\Yaml\Yaml;

/**
 * Serves interactive API documentation (Swagger UI) and the underlying
 * OpenAPI specification generated by `anvil:generate --openapi`.
 *
 * Routes (registered by LaravelAnvilServiceProvider when
 * config('anvil.openapi.docs.enabled') is true):
 *
 *   GET {prefix}                      → Swagger UI HTML page
 *   GET {prefix}/openapi.{yaml|json}  → the root spec, BUNDLED
 *   GET {prefix}/{file}               → any split $ref file (raw)
 *
 * Why bundle the root spec:
 *   In split-file mode the root references external files
 *   (./schemas/X.yaml#/X, ./paths/Y.yaml#/...). The operations inside those
 *   path files use absolute internal pointers like #/components/schemas/X,
 *   which only resolve against the document they live in — and a path file has
 *   no `components` section, so Swagger UI throws "JSON Pointer evaluation
 *   failed ... 'components'". Bundling inlines the external files into one
 *   self-contained document so every #/components/... ref resolves. In
 *   single-file mode there are no external refs, so bundling is a harmless
 *   no-op.
 */
class DocsController
{
    public function ui(Request $request): Response
    {
        $ext     = $this->extension();
        $specUrl = url($this->prefix().'/openapi.'.$ext);

        return new Response(
            $this->html($specUrl),
            200,
            ['Content-Type' => 'text/html; charset=UTF-8'],
        );
    }

    public function spec(Request $request, ?string $file = null): Response
    {
        $base = $this->specBasePath();
        $ext  = $this->extension();

        if (! is_dir($base)) {
            return $this->missingSpecResponse();
        }

        $rootName = 'openapi.'.$ext;
        $file = $file ?: $rootName;

        $candidate = realpath($base.DIRECTORY_SEPARATOR.$file);
        $baseReal  = realpath($base);

        if ($candidate === false || $baseReal === false || ! str_starts_with($candidate, $baseReal)) {
            return new Response("Spec file not found: {$file}", 404, ['Content-Type' => 'text/plain']);
        }

        $isJson      = str_ends_with($candidate, '.json');
        $contentType = $isJson ? 'application/json' : 'application/yaml';

        // The root spec is bundled; sub-files are served raw (handy for debugging).
        $body = ($file === $rootName)
            ? $this->bundle($candidate, $isJson ? 'json' : 'yaml')
            : file_get_contents($candidate);

        return new Response($body, 200, [
            'Content-Type'                => $contentType,
            'Access-Control-Allow-Origin' => '*',
            'Cache-Control'               => 'no-cache',
        ]);
    }

    // -----------------------------------------------------------------------
    // Bundler
    // -----------------------------------------------------------------------

    /**
     * Produce a self-contained spec by inlining first-level external file refs
     * (./schemas/*, ./paths/*) into the root document. Internal #/... refs are
     * left untouched — once their targets are inlined they resolve within the
     * single bundled document.
     */
    protected function bundle(string $rootFile, string $format): string
    {
        try {
            $base = dirname($rootFile);
            $root = $this->parse($rootFile, $format);

            if ($root === []) {
                return file_get_contents($rootFile);
            }

            if (isset($root['components']['schemas']) && is_array($root['components']['schemas'])) {
                foreach ($root['components']['schemas'] as $name => $def) {
                    $resolved = $this->resolveExternalRef($def, $base, $format);
                    if ($resolved !== null) {
                        $root['components']['schemas'][$name] = $resolved;
                    }
                }
            }

            if (isset($root['paths']) && is_array($root['paths'])) {
                foreach ($root['paths'] as $key => $def) {
                    $resolved = $this->resolveExternalRef($def, $base, $format);
                    if ($resolved !== null) {
                        $root['paths'][$key] = $resolved;
                    }
                }
            }

            return $this->dump($root, $format);
        } catch (\Throwable $e) {
            // Never let bundling break the docs — fall back to the raw root file.
            return file_get_contents($rootFile);
        }
    }

    /**
     * If $def is a single external {$ref: './file#/pointer'}, load and return
     * the referenced sub-tree. Returns null for non-refs and internal #/ refs.
     *
     * @param  mixed  $def
     * @return array<mixed>|null
     */
    protected function resolveExternalRef($def, string $base, string $format): ?array
    {
        if (! is_array($def) || ! isset($def['$ref']) || count($def) !== 1) {
            return null;
        }

        $ref = $def['$ref'];
        if (! is_string($ref) || $ref === '' || str_starts_with($ref, '#')) {
            return null; // internal ref — leave for in-document resolution
        }

        [$relFile, $fragment] = array_pad(explode('#', $ref, 2), 2, '');
        $relFile = preg_replace('#^\./#', '', (string) $relFile);

        $target   = realpath($base.DIRECTORY_SEPARATOR.$relFile);
        $baseReal = realpath($base);

        if ($target === false || $baseReal === false || ! str_starts_with($target, $baseReal)) {
            return null;
        }

        $data = $this->parse($target, $format);
        $resolved = $this->pointerGet($data, (string) $fragment);

        return is_array($resolved) ? $resolved : null;
    }

    /**
     * Resolve an RFC 6901 JSON Pointer against a parsed document.
     *
     * @param  array<mixed>  $data
     * @return mixed
     */
    protected function pointerGet(array $data, string $fragment)
    {
        $fragment = ltrim($fragment, '/');
        if ($fragment === '') {
            return $data;
        }

        $cursor = $data;
        foreach (explode('/', $fragment) as $token) {
            $token = str_replace(['~1', '~0'], ['/', '~'], $token);

            if (is_array($cursor) && array_key_exists($token, $cursor)) {
                $cursor = $cursor[$token];
            } else {
                return null;
            }
        }

        return $cursor;
    }

    // -----------------------------------------------------------------------
    // Parse / dump
    // -----------------------------------------------------------------------

    /**
     * @return array<mixed>
     */
    protected function parse(string $file, string $format): array
    {
        $raw = @file_get_contents($file);
        if ($raw === false || $raw === '') {
            return [];
        }

        $data = $format === 'json'
            ? json_decode($raw, true)
            : Yaml::parse($raw);

        return is_array($data) ? $data : [];
    }

    /**
     * @param  array<mixed>  $data
     */
    protected function dump(array $data, string $format): string
    {
        if ($format === 'json') {
            return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        }

        $flags = Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK;
        if (defined(Yaml::class.'::DUMP_EMPTY_ARRAY_AS_SEQUENCE')) {
            $flags |= Yaml::DUMP_EMPTY_ARRAY_AS_SEQUENCE;
        }

        return Yaml::dump($data, 20, 2, $flags);
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    protected function prefix(): string
    {
        return trim(config('anvil.openapi.docs.route', 'docs'), '/');
    }

    protected function extension(): string
    {
        return config('anvil.openapi.format', 'yaml') === 'json' ? 'json' : 'yaml';
    }

    protected function specBasePath(): string
    {
        return base_path(config('anvil.openapi.output_path', 'openapi'));
    }

    protected function missingSpecResponse(): Response
    {
        $msg = "OpenAPI spec not found. Run: php artisan anvil:generate --openapi";

        return new Response($msg, 404, ['Content-Type' => 'text/plain']);
    }

    protected function html(string $specUrl): string
    {
        $title   = config('anvil.openapi.title', config('app.name', 'API Docs'));
        $version = config('anvil.openapi.docs.ui_version', '5.17.14');

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{$title} — API Documentation</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@{$version}/swagger-ui.css" />
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
    #swagger-ui .topbar { display: none; }
    .anvil-header {
      background: #1a1a2e; color: #fff; padding: 16px 24px;
      display: flex; align-items: center; gap: 12px;
      font-size: 18px; font-weight: 600; letter-spacing: 0.5px;
    }
    .anvil-header span { opacity: 0.6; font-size: 13px; font-weight: 400; }
  </style>
</head>
<body>
  <div class="anvil-header">
    &#9874; {$title} <span>API Documentation</span>
  </div>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@{$version}/swagger-ui-bundle.js"></script>
  <script src="https://unpkg.com/swagger-ui-dist@{$version}/swagger-ui-standalone-preset.js"></script>
  <script>
    window.onload = () => {
      SwaggerUIBundle({
        url: '{$specUrl}',
        dom_id: '#swagger-ui',
        presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
        layout: 'StandaloneLayout',
        deepLinking: true,
        displayRequestDuration: true,
        defaultModelsExpandDepth: 2,
        tryItOutEnabled: true,
        filter: true,
      });
    };
  </script>
</body>
</html>
HTML;
    }
}