<?php

namespace Zuqongtech\LaravelAnvil\Http;

use Illuminate\Http\Response;
use Symfony\Component\Yaml\Yaml;

/**
 * Serves interactive API documentation (Swagger UI) and the underlying
 * OpenAPI specification generated by `anvil:generate --openapi`.
 *
 * Routes (registered by LaravelAnvilServiceProvider when
 * config('anvil.openapi.docs.enabled') is true):
 *
 *   GET {prefix}                      → Swagger UI HTML page
 *   GET {prefix}/openapi.{yaml|json}  → the root spec, BUNDLED
 *   GET {prefix}/{file}               → any split $ref file (raw)
 *
 * Why bundle the root spec:
 *   In split-file mode the root references external files
 *   (./schemas/X.yaml#/X, ./paths/Y.yaml#/...). The operations inside those
 *   path files use absolute internal pointers like #/components/schemas/X,
 *   which only resolve against the document they live in — and a path file has
 *   no `components` section, so Swagger UI throws "JSON Pointer evaluation
 *   failed ... 'components'". Bundling inlines the external files into one
 *   self-contained docfinal ument so every #/components/... ref resolves. In
 *   single-file mode there are no external refs, so bundling is a harmless
 *   no-op.
 */
class DocsController
{
    // -----------------------------------------------------------------------
    // Bundler
    // -----------------------------------------------------------------------

    /**
     * Produce a self-contained spec by inlining first-level external file refs
     * (./schemas/*, ./paths/*) into the root document. Internal #/... refs are
     * left untouched — once their targets are inlined they resolve within the
     * single bundled document.
     */
    protected function bundle(string $rootFile, string $format): string|false
    {
        try {
            $base = dirname($rootFile);
            $root = $this->parse($rootFile, $format);

            if ($root === []) {
                return file_get_contents($rootFile);
            }

            if (isset($root['components']['schemas']) && is_array($root['components']['schemas'])) {
                foreach ($root['components']['schemas'] as $name => $def) {
                    $resolved = $this->resolveExternalRef($def, $base, $format);
                    if ($resolved !== null) {
                        $root['components']['schemas'][$name] = $resolved;
                    }
                }
            }

            if (isset($root['paths']) && is_array($root['paths'])) {
                foreach ($root['paths'] as $key => $def) {
                    $resolved = $this->resolveExternalRef($def, $base, $format);
                    if ($resolved !== null) {
                        $root['paths'][$key] = $resolved;
                    }
                }
            }

            return $this->dump($root, $format);
        } catch (\Throwable $e) {
            // Never let bundling break the docs — fall back to the raw root file.
            return file_get_contents($rootFile);
        }
    }

    /**
     * If $def is a single external {$ref: './file#/pointer'}, load and return
     * the referenced sub-tree. Returns null for non-refs and internal #/ refs.
     *
     * @param  mixed  $def
     * @return array<mixed>|null
     */
    protected function resolveExternalRef($def, string $base, string $format): ?array
    {
        if (! is_array($def) || ! isset($def['$ref']) || count($def) !== 1) {
            return null;
        }

        $ref = $def['$ref'];
        if (! is_string($ref) || $ref === '' || str_starts_with($ref, '#')) {
            return null; // internal ref — leave for in-document resolution
        }

        [$relFile, $fragment] = array_pad(explode('#', $ref, 2), 2, '');
        $relFile = preg_replace('#^\./#', '', (string) $relFile);

        $target = realpath($base.DIRECTORY_SEPARATOR.$relFile);
        $baseReal = realpath($base);

        if ($target === false || $baseReal === false || ! str_starts_with($target, $baseReal)) {
            return null;
        }

        $data = $this->parse($target, $format);
        $resolved = $this->pointerGet($data, (string) $fragment);

        return is_array($resolved) ? $resolved : null;
    }

    /**
     * Resolve an RFC 6901 JSON Pointer against a parsed document.
     *
     * @param  array<mixed>  $data
     * @return mixed
     */
    protected function pointerGet(array $data, string $fragment)
    {
        $fragment = ltrim($fragment, '/');
        if ($fragment === '') {
            return $data;
        }

        $cursor = $data;
        foreach (explode('/', $fragment) as $token) {
            $token = str_replace(['~1', '~0'], ['/', '~'], $token);

            if (is_array($cursor) && array_key_exists($token, $cursor)) {
                $cursor = $cursor[$token];
            } else {
                return null;
            }
        }

        return $cursor;
    }

    // -----------------------------------------------------------------------
    // Parse / dump
    // -----------------------------------------------------------------------

    /**
     * @return array<mixed>
     */
    protected function parse(string $file, string $format): array
    {
        $raw = @file_get_contents($file);
        if ($raw === false || $raw === '') {
            return [];
        }

        $data = $format === 'json'
            ? json_decode($raw, true)
            : Yaml::parse($raw);

        return is_array($data) ? $data : [];
    }

    /**
     * @param  array<mixed>  $data
     */
    protected function dump(array $data, string $format): string|false
    {
        if ($format === 'json') {
            return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        }

        $flags = Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK;
        if (defined(Yaml::class.'::DUMP_EMPTY_ARRAY_AS_SEQUENCE')) {
            $flags |= Yaml::DUMP_EMPTY_ARRAY_AS_SEQUENCE;
        }

        return Yaml::dump($data, 20, 2, $flags);
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    protected function prefix(): string
    {
        return trim(config('anvil.openapi.docs.route', 'docs'), '/');
    }

    protected function extension(): string
    {
        return config('anvil.openapi.format', 'yaml') === 'json' ? 'json' : 'yaml';
    }

    protected function specBasePath(): string
    {
        return base_path(config('anvil.openapi.output_path', 'openapi'));
    }

    protected function missingSpecResponse(): Response
    {
        $msg = 'OpenAPI spec not found. Run: php artisan anvil:generate --openapi';

        return new Response($msg, 404, ['Content-Type' => 'text/plain']);
    }

    protected function html(string $specUrl): string
    {
        $title = config('anvil.openapi.title', config('app.name', 'API Docs'));
        $version = config('anvil.openapi.docs.ui_version', '5.17.14');

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{$title} — API Documentation</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@{$version}/swagger-ui.css" />
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
    #swagger-ui .topbar { display: none; }
 
    .anvil-header {
      background: #1a1a2e;
      color: #fff;
      padding: 14px 28px;
      display: flex;
      align-items: center;
      gap: 14px;
    }
    .anvil-logo {
      width: 46px;
      height: 46px;
      flex: 0 0 auto;
      display: block;
    }
    .anvil-title {
      font-size: 20px;
      font-weight: 700;
      letter-spacing: 0.3px;
      line-height: 1;
    }
    .anvil-divider {
      width: 1px;
      height: 26px;
      background: rgba(255, 255, 255, 0.18);
      margin: 0 2px;
    }
    .anvil-sub {
      font-size: 13px;
      font-weight: 400;
      opacity: 0.55;
      letter-spacing: 0.2px;
    }
  </style>
</head>
<body>
  <header class="anvil-header">
    <svg class="anvil-logo" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Laravel Anvil logo">
      <defs>
        <linearGradient id="anvil-bg" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#272b46"/>
          <stop offset="1" stop-color="#14152a"/>
        </linearGradient>
        <linearGradient id="anvil-steel" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#F6F8FD"/>
          <stop offset="0.55" stop-color="#DDE3EF"/>
          <stop offset="1" stop-color="#B7C0D2"/>
        </linearGradient>
        <linearGradient id="anvil-head" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#E7ECF5"/>
          <stop offset="1" stop-color="#9AA4B8"/>
        </linearGradient>
        <linearGradient id="anvil-red" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#FF4133"/>
          <stop offset="1" stop-color="#D7190D"/>
        </linearGradient>
      </defs>
 
      <rect x="24" y="24" width="464" height="464" rx="108" fill="url(#anvil-bg)"/>
      <rect x="25.5" y="25.5" width="461" height="461" rx="106.5" fill="none" stroke="#3a3f5e" stroke-width="3"/>
 
      <g transform="translate(256 300) rotate(-45)" stroke="#15131c" stroke-linejoin="round">
        <rect x="-15" y="-118" width="30" height="272" rx="15" fill="url(#anvil-red)" stroke-width="3"/>
        <rect x="-16" y="118" width="32" height="8" rx="4" fill="#9e120a" stroke="none"/>
        <rect x="-16" y="132" width="32" height="8" rx="4" fill="#9e120a" stroke="none"/>
        <rect x="-23" y="-106" width="46" height="22" rx="6" fill="url(#anvil-head)" stroke-width="2.5"/>
        <rect x="-66" y="-154" width="132" height="62" rx="12" fill="url(#anvil-head)" stroke-width="3"/>
        <rect x="40" y="-150" width="22" height="54" rx="7" fill="#8B94A8" stroke="none"/>
        <rect x="-58" y="-148" width="14" height="40" rx="6" fill="#FBFCFF" opacity="0.6" stroke="none"/>
      </g>
 
      <g transform="translate(256 300) rotate(45)" stroke="#15131c" stroke-linejoin="round">
        <rect x="-15" y="-118" width="30" height="272" rx="15" fill="url(#anvil-red)" stroke-width="3"/>
        <rect x="-16" y="118" width="32" height="8" rx="4" fill="#9e120a" stroke="none"/>
        <rect x="-16" y="132" width="32" height="8" rx="4" fill="#9e120a" stroke="none"/>
        <rect x="-23" y="-106" width="46" height="22" rx="6" fill="url(#anvil-head)" stroke-width="2.5"/>
        <rect x="-66" y="-154" width="132" height="62" rx="12" fill="url(#anvil-head)" stroke-width="3"/>
        <rect x="-62" y="-150" width="22" height="54" rx="7" fill="#8B94A8" stroke="none"/>
        <rect x="44" y="-148" width="14" height="40" rx="6" fill="#FBFCFF" opacity="0.6" stroke="none"/>
      </g>
 
      <ellipse cx="256" cy="410" rx="116" ry="16" fill="#000000" opacity="0.28"/>
 
      <g stroke="#15131c" stroke-width="4" stroke-linejoin="round">
        <path d="M212 292 L300 292 L288 330 L320 354 L336 398 L176 398 L192 354 L224 330 Z" fill="url(#anvil-steel)"/>
        <path d="M116 270 L162 252 L358 252 L358 276 L300 292 L164 292 L140 286 Z" fill="url(#anvil-steel)"/>
      </g>
 
      <rect x="172" y="255" width="180" height="9" rx="4.5" fill="#FFFFFF" opacity="0.65"/>
      <path d="M224 330 L288 330 L283 344 L229 344 Z" fill="#0d0f1f" opacity="0.12"/>
 
      <g fill="#FF6A4A">
        <path d="M372 222 l5 12 12 5 -12 5 -5 12 -5 -12 -12 -5 12 -5 z"/>
        <circle cx="392" cy="250" r="4"/>
      </g>
    </svg> 
    <span class="anvil-title">{$title}</span>
    <span class="anvil-divider"></span>
    <span class="anvil-sub">API Documentation</span>
  </header>

  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@{$version}/swagger-ui-bundle.js"></script>
  <script src="https://unpkg.com/swagger-ui-dist@{$version}/swagger-ui-standalone-preset.js"></script>
  <script>
    window.onload = () => {
      SwaggerUIBundle({
        url: '{$specUrl}',
        dom_id: '#swagger-ui',
        presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
        layout: 'StandaloneLayout',
        deepLinking: true,
        displayRequestDuration: true,
        defaultModelsExpandDepth: 2,
        tryItOutEnabled: true,
        filter: true,
      });
    };
  </script>
</body>
</html>
HTML;
    }
}
